version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: web_library
      MYSQL_USER: web_library_user
      MYSQL_PASSWORD: web_library_123
    ports:
      - "3306:3306"
    volumes:
      - db_data_web_library:/var/lib/mysql
    networks:
      - web_library_network

  app:
    container_name: app_container
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/web_library
      SPRING_DATASOURCE_USERNAME: web_library_user
      SPRING_DATASOURCE_PASSWORD: web_library_123
    ports:
      - "80:80"
    depends_on:
      - mysql
    networks:
      - web_library_network

networks:
  web_library_network:
    driver: bridge

volumes:
  db_data_web_library:
