INSERT INTO web_library.books (bok_author, bok_description, bok_gender, bok_isbn, bok_publication_date, bok_title)
VALUES ('Martin Fowler',
        'Um guia essencial para qualquer desenvolvedor de software que deseja entender e aplicar técnicas de design de software e padrões arquitetônicos.',
        'Computação', '978-0-13-475759-9', '2018-10-15', 'Refactoring: Improving the Design of Existing Code'),
       ('Robert C. Martin',
        'Um livro que apresenta princípios, práticas e padrões para desenvolvimento ágil de software com qualidade e manutenibilidade.',
        'Computação', '978-0-13-235088-4', '2008-08-11', 'Clean Code: A Handbook of Agile Software Craftsmanship'),
       ('Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides',
        'Um clássico que apresenta 23 padrões de design de software que têm como objetivo resolver problemas comuns no desenvolvimento de software.',
        'Computação', '978-0-20-163361-0', '1994-10-31', 'Design Patterns: Elements of Reusable Object-Oriented Software'),
       ('Kent Beck',
        'Um guia completo para a prática de desenvolvimento de software usando a metodologia de Desenvolvimento Orientado a Testes (TDD).',
        'Computação', '978-0-32-114653-3', '2002-08-15', 'Test-Driven Development: By Example'),
       ('Joshua Bloch',
        'Um livro abrangente sobre a linguagem de programação Java, cobrindo conceitos fundamentais e avançados.',
        'Computação', '978-0-13-468599-1', '2018-01-11', 'Effective Java'),
       ('Martin Fowler', 'Explora a importância da arquitetura de software e como implementá-la efetivamente.',
        'Computação', '978-0-13-475759-9', '2014-05-12', 'Patterns of Enterprise Application Architecture'),
       ('Steve McConnell',
        'Uma análise completa das melhores práticas em desenvolvimento de software, com dicas e técnicas para melhorar a produtividade e qualidade.',
        'Computação', '978-0-73-561967-8', '2004-01-01', 'Code Complete: A Practical Handbook of Software Construction'),
       ('Andrew S. Tanenbaum',
        'Um livro clássico sobre sistemas operacionais, cobrindo teoria e prática de sistemas operacionais modernos.',
        'Computação', '978-0-13-359162-0', '2014-08-20', 'Modern Operating Systems'),
       ('Donald E. Knuth',
        'Um dos trabalhos mais influentes em algoritmos e análise de complexidade, apresentado em uma série de volumes.',
        'Computação', '978-0-20-103803-6', '1997-09-01', 'The Art of Computer Programming'),
       ('Robert C. Martin',
        'Explora os princípios e práticas que ajudam os desenvolvedores a criar código de alta qualidade e manutenível.',
        'Computação', '978-01-370-5233-0', '2009-08-01', 'Clean Agile: Back to Basics'),
       ('Douglas Crockford', 'Um livro sobre a linguagem JavaScript e melhores práticas para seu uso.', 'Computação',
        '978-0596517748', '2008-05-15', 'JavaScript: The Good Parts'),
       ('Ian Sommerville',
        'Um texto abrangente sobre engenharia de software, cobrindo o ciclo de vida do desenvolvimento de software.',
        'Computação', '978-0-13-394303-0', '2015-07-06', 'Software Engineering'),
       ('Scott Meyers',
        'Um livro sobre os princípios e técnicas de programação C++, focado em otimização e eficiência.', 'Computação',
        '978-0-20-182470-7', '2001-07-01',
        'Effective STL: 50 Specific Ways to Improve Your Use of the Standard Template Library'),
       ('James Gosling, Bill Joy', 'O livro oficial sobre a linguagem de programação Java, escrita por seus criadores.',
        'Computação', '978-0-13-468599-1', '2014-11-11', 'The Java Programming Language'),
       ('Michael T. Goodrich, Roberto Tamassia', 'Um livro sobre estruturas de dados e algoritmos com foco em Java.',
        'Computação', '978-1-11-829027-9', '2014-04-09', 'Data Structures and Algorithms in Java');

